language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get install -y swig libgphoto2-dev

script:
  - python setup.py build_swig
  - PYTHON_GPHOTO2_BUILTIN=1 python setup.py build
  - rm -rf build
  - PYTHON_GPHOTO2_NO_BUILTIN=1 python setup.py build
  - rm -rf build
  - PYTHON_GPHOTO2_BUILTIN=1 CC=clang python setup.py build
  - rm -rf build
  - PYTHON_GPHOTO2_NO_BUILTIN=1 CC=clang python setup.py build
